-- oracle DB definition
CREATE TABLE "tkeyuser" (
    "iduser" NUMBER(*, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "dtname" VARCHAR2(40),
    "dtmaxSize" NUMBER(*, 0),
    PRIMARY KEY ("iduser") USING INDEX ENABLE
);